version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-nuxt-app:/app
    environment:
      - HOST=0.0.0.0
    depends_on:
      - api
  api:
    image: your-api-image:tag  # Replace with your API image details
    ports:
      - "4000:4000"

